#!/bin/bash

tune_folder="/home/gaudu/pyapprentice-1.1.0/bin/tune2/"

if [ -d "$tune_folder" ]; then
    folders=$(find "$tune_folder" -mindepth 1 -maxdepth 1 -type d | wc -l)
else
    echo "folder not found: $tune_folder"
fi

for ((i=0; i<$folders; i++)); do
    formatted_i=$(printf "%02d" $i)
    template_path=$tune_folder"$formatted_i/template.dat"

    if [ -e "$template_path" ]; then
        mapfile -t lines < "$template_path"        
    else
        echo "File not found: $template_path"
    fi

    for ((i=0; i<${#lines[@]}; i++)); do
        lines[i]=${lines[i]// /}
    done

    ./main1009 $formatted_i ${lines[0]} ${lines[1]} ${lines[2]}
done