#!/bin/bash

tune_folder="/home/gaudu/pyapprentice-1.1.0/bin/tune2/"

if [ -d "$tune_folder" ]; then
    folders=$(find "$tune_folder" -mindepth 1 -maxdepth 1 -type d | wc -l)
else
    echo "folder not found: $tune_folder"
fi

for ((i=0; i<$folders; i++)); do
    formatted_i=$(printf "%02d" $i)
    template_path=$tune_folder"$formatted_i/template.dat"
    
    if [ -e "$template_path" ]; then
        mapfile -t lines < "$template_path"        
    else
        echo "File not found: $template_path"
    fi
    
    for ((j=0; j<${#lines[@]}; j++)); do
        lines[j]=${lines[j]// /}
    done
    	    
    ./main1009 158 $formatted_i ${lines[0]} ${lines[1]} ${lines[2]} && ./main1009 350 $formatted_i ${lines[0]} ${lines[1]} ${lines[2]}

    cat main1009_tune2_158_"$formatted_i"_10000.yoda main1009_tune2_350_"$formatted_i"_10000.yoda > main1009_tune2_"$formatted_i"_10000.yoda
done